import AstroSitemap from '@astrojs/sitemap';
import type { AstroIntegration } from 'astro';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { normalizeLangTag } from '../src/i18n/bcp-normalize';
import languages from '../src/i18n/languages';

const langTags = Object.keys(languages);

/** Set matching our `/[lang]/something.astro` redirect routes. */
const blocklist = new Set([
	...langTags.map((lang) => `/${lang}/`),
	...langTags.map((lang) => `/${lang}/install/`),
	...langTags.map((lang) => `/${lang}/tutorial/`),
]);

/** Match a pathname starting with “lighthouse” or one of our language tags. */
const ValidRouteRE = new RegExp(`^/(lighthouse|${langTags.join('|')})/`);

const PAGES_DIR = fileURLToPath(new URL('../src/pages', import.meta.url));

/**
 * Walk a language's pages directory and return the set of pathnames
 * that correspond to real `.mdx` files (i.e. actually-translated pages),
 * in the same form the sitemap emits: `/{lang}/path/to/page/`.
 */
const collectRealPaths = (lang: string): Set<string> => {
	const paths = new Set<string>();
	const langDir = path.join(PAGES_DIR, lang);
	if (!fs.existsSync(langDir)) return paths;

	const walk = (dir: string) => {
		for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
			const full = path.join(dir, entry.name);
			if (entry.isDirectory()) {
				walk(full);
			} else if (entry.isFile() && entry.name.endsWith('.mdx')) {
				const rel = path.relative(PAGES_DIR, full).split(path.sep).join('/');
				// strip trailing .mdx and add trailing slash, matching Astro's output URLs
				const url = '/' + rel.replace(/\.mdx$/, '') + '/';
				paths.add(url);
			}
		}
	};

	walk(langDir);
	return paths;
};

/**
 * Build a set of every URL we want in the sitemap. For each language, only
 * include pages that have a real `.mdx` translation — skip fallback pages
 * generated by `src/pages/[lang]/[...fallback].astro`, which would otherwise
 * duplicate English content under every language prefix.
 */
const buildAllowedPaths = (): Set<string> => {
	const allowed = new Set<string>();
	for (const lang of langTags) {
		for (const p of collectRealPaths(lang)) allowed.add(p);
	}
	return allowed;
};

const allowedPaths = buildAllowedPaths();

/** Test a pathname is not in our blocklist, starts with a valid prefix, and is a real translated page. */
const isValidPath = (pathname: string) => {
	if (blocklist.has(pathname)) return false;
	if (!ValidRouteRE.test(pathname)) return false;
	// Always allow lighthouse routes (not language-gated)
	if (pathname.startsWith('/lighthouse/')) return true;
	return allowedPaths.has(pathname);
};

/** Get a preconfigured instance of the `@astrojs/sitemap` integration. */
export function sitemap(): AstroIntegration {
	return AstroSitemap({
		filter: (page) => isValidPath(new URL(page).pathname),
		i18n: {
			defaultLocale: 'en',
			locales: Object.fromEntries(langTags.map((lang) => [lang, normalizeLangTag(lang)])),
		},
	});
}
